Add Barbar support
uloco/bluloco.nvim pull request #3
Opened 2022-12-17 21:25 UTC by James-DeLorenzo

here is some sample images and the text highlighted via running `lushify` on the theme file;
![sample_barbar_9](https://user-images.githubusercontent.com/19446243/208266333-8b191c7a-024f-4767-868e-969c358e1f5d.png)

plugins.lua is an inactive buffer, not shown in any current window
test.py was the last buffer visible, using the alternate highlighting (when highlight_alertnate is false in settings this highlight does not show and shows like plugins.lua)
init.lua is the currently open buffer
bluloco-dark.lua is a buffer that is visible in a window but not the active window/buffer

samples via `Lushify` call;
![sample_barbar_6](https://user-images.githubusercontent.com/19446243/208266187-c7e6e61b-5d3f-4c46-b12d-d3f8d83fc5c8.png)
![sample_barbar_7](https://user-images.githubusercontent.com/19446243/208266193-6c8bab86-cf27-4ec4-8710-e7fbc29e77c9.png)

2022-12-18 21:57 UTC, uloco requested changes
Thank you so much for this PR :)

I have some minor nitpicks, that would improve things in my opinion:

* You could use t.type als a fg for all target highlights, so it's better visible
* I think the alternate buffer is too visible, how about we keep the text as BufferInactive but just highlight the BufferAlternateSign with t.constant?
* To make this also work with transparent mode, we should add the bgs to the init.lua transparent section.
```lua
BufferInactive { theme.BufferInactive, bg = "NONE" },
BufferVisible { BufferCurrent }
```

2022-12-18 21:57 UTC, uloco commented on lua/lush_theme/bluloco.lua
> +    BufferCurrentTarget { fg = shade(t.error, 40), bg = BufferCurrent.bg },
Let's use the red from types, and stay consistent for all buffers so it's easier for the eyes? I have added suggestsions for those down below also.
```suggestion
    BufferCurrentTarget { BufferCurrent, fg = t.type },
```

2022-12-18 21:57 UTC, uloco commented on lua/lush_theme/bluloco.lua
> +    BufferInactiveTarget { fg = shade(BufferInactive.fg, 70), bg = BufferInactive.bg },
```suggestion
    BufferInactiveTarget { BufferInactive, fg = t.type },
```

2022-12-18 21:57 UTC, uloco commented on lua/lush_theme/bluloco.lua
> +    BufferVisibleTarget { fg = shade(BufferVisible.fg, 70), bg = BufferVisible.bg },
```suggestion
    BufferVisibleTarget { BufferVisible, fg = t.type },
```

2022-12-18 21:57 UTC, uloco commented on lua/lush_theme/bluloco.lua
> +    BufferAlternateTarget { BufferInactiveTarget, fg = shade(BufferAlternate.fg, 70) },
```suggestion
    BufferAlternateTarget { BufferAlternate, fg = t.type},
```

2022-12-18 21:57 UTC, uloco commented on lua/lush_theme/bluloco.lua
> +    BufferAlternate { BufferInactive, fg = t.tag },
I think this is just too much for a alternate buffer, probalby the sign only would be better, see below
```suggestion
    BufferAlternate { BufferInactive },
```

2022-12-18 21:57 UTC, uloco commented on lua/lush_theme/bluloco.lua
> +    BufferAlternateSign { BufferInactiveSign },
blue would be just too close to the actual current one. how about purple for alternate sign?
```suggestion
    BufferAlternateSign { BufferInactiveSign, fg = t.constant },
```

2022-12-18 21:57 UTC, uloco commented on lua/lush_theme/bluloco.lua
> +    BufferCurrent { fg = t.fg, bg = t.bg },
I'd like the bufferline to be transparent also if enabled, so using Normal here would be better
```suggestion
    BufferCurrent { Normal },
```

2022-12-18 21:57 UTC, uloco commented on lua/lush_theme/bluloco.lua
> +    BufferTabpageFill { BufferTabpages, fg = t.shade3 },
```suggestion
    BufferTabpageFill { BufferTabpages, fg = t.bg },
```

2022-12-18 21:57 UTC, uloco commented on lua/lush_theme/bluloco.lua
> +    BufferTabpages { BufferInactive, fg = t.shade90 },
```suggestion
    BufferTabpages { BufferInactive, fg = t.fg },
```

2022-12-22 00:58 UTC, James-DeLorenzo commented on lua/lush_theme/bluloco.lua
> +    BufferAlternateSign { BufferInactiveSign },
ok, here's how that looks now;
![image](https://user-images.githubusercontent.com/19446243/209031862-5f7be98f-49ed-446c-94d4-18aa833a9330.png)

2022-12-22 09:26 UTC, uloco commented on lua/lush_theme/bluloco.lua
> +    BufferAlternateSign { BufferInactiveSign },
I like it, thanks :)

2022-12-22 09:28 UTC, uloco approved these changes
Love it, thank you so much again :)

2022-12-22 09:28 UTC, merged